#! /bin/sh

if [ -x /usr/bin/gtk-update-icon-cache ]
then
  /usr/bin/gtk-update-icon-cache -f /usr/share/icons/hicolor
fi

if [ -x /usr/bin/update-desktop-database ]
then
  /usr/bin/update-desktop-database
fi

if [ -x /usr/bin/update-mime-database ]
then
  /usr/bin/update-mime-database /usr/share/mime
fi

if [ "$1" = "configure" -a -z "$2" -a -x /usr/bin/maemo-select-menu-location ]
then
	/usr/bin/maemo-select-menu-location FBReader.desktop
fi
